// Generated by https://github.com/foxglove/schemas

import { Color } from "./Color";
import { Pose } from "./Pose";

/** A marker representing an arrow */
export type ArrowMarker = {
  /** Position of the arrow's tail and orientation of the arrow. Identity orientation means the arrow points in the +x direction. */
  pose: Pose;

  /** Length of the arrow */
  length: number;

  /** Diameter of the arrow shaft */
  shaft_diameter: number;

  /** Diameter of the arrow head */
  head_diameter: number;

  /** Length of the arrow head */
  head_length: number;

  /** Color of the arrow */
  color: Color;
};
