// Generated by https://github.com/foxglove/schemas

/** A color in RGBA format */
export type Color = {
  /** Red value between 0 and 1 */
  r: number;

  /** Green value between 0 and 1 */
  g: number;

  /** Blue value between 0 and 1 */
  b: number;

  /** Alpha value between 0 and 1 */
  a: number;
};
