// Generated by https://github.com/foxglove/schemas
// Options: {}

import { Time } from "./Time";

/** A single frame of a compressed audio bitstream */
export type CompressedAudio = {
  /** Timestamp of audio frame */
  timestamp: Time;

  /** Compressed audio frame data. */
  data: Uint8Array;

  /**
   * Audio format.
   * 
   * Supported values: `opus`.
   */
  format: string;

  /**
   * Frame type.
   * 
   *  Supported values: `key`, `delta`.
   */
  type: string;

  /** Number of audio samples per second. */
  sample_rate: number;

  /** Number of audio channels in the input. */
  number_of_channels: number;
};
