// Generated by https://github.com/foxglove/schemas
// Options: {}

import { Time } from "./Time";

/** A single frame of a compressed audio bitstream */
export type CompressedAudio = {
  /** Timestamp of audio frame */
  timestamp: Time;

  /**
   * Compressed audio frame data.
   * 
   * TK
   */
  data: Uint8Array;

  /**
   * Audio format.
   * 
   * Supported values: `opus`.
   */
  format: string;
};
