// Generated by https://github.com/foxglove/schemas

import { Color } from "./Color";
import { Pose } from "./Pose";
import { Vector3 } from "./Vector3";

/** A primitive representing a possibly truncated, possibly elliptic cone or cylinder */
export type ConePrimitive = {
  /** Position of the center of the cone and orientation of the cone. The flat face(s) are perpendicular to the z-axis. */
  pose: Pose;

  /** Size of the cone's bounding box */
  size: Vector3;

  /** 0-1, size of the cone's bottom face (min z) relative to the bottom of the bounding box */
  bottom_scale: number;

  /** 0-1, size of the cone's top face (max z) relative to the top of the bounding box */
  top_scale: number;

  /** Color of the cone */
  color: Color;
};
