// Generated by https://github.com/foxglove/schemas

import { Color } from "./Color";
import { KeyValuePair } from "./KeyValuePair";
import { Pose } from "./Pose";
import { Vector3 } from "./Vector3";

/** A primitive representing a cube or rectangular prism */
export type CubePrimitive = {
  /** Position of the center of the cube and orientation of the cube */
  pose: Pose;

  /** Size of the cube along each axis */
  size: Vector3;

  /** Color of the arrow */
  color: Color;

  /** Additional user-provided metadata associated with the cube. Keys must be unique. */
  metadata: KeyValuePair[];
};
