// Generated by https://github.com/foxglove/schemas

/** a single key-value pair of metadata for an event */
export type EventKeyValue = {
  /** key for this metadata */
  key: string;

  /** value of the metadata */
  value: string;
};
