// Generated by https://github.com/foxglove/schemas

import { FrameTransform } from "./FrameTransform";

/** A list of transforms between reference frames in 3D space */
export type FrameTransformList = {
  /** List of transforms */
  transforms: FrameTransform[];
};
