// Generated by https://github.com/foxglove/schemas

/** (Experimental, subject to change) A key with its associated value */
export type KeyValuePair = {
  /** Key */
  key: string;

  /** Value */
  value: string;
};
