// Generated by https://github.com/foxglove/schemas

import { ArrowMarker } from "./ArrowMarker";
import { ConeListMarker } from "./ConeListMarker";
import { CubeListMarker } from "./CubeListMarker";
import { LineMarker } from "./LineMarker";
import { MarkerDeletion } from "./MarkerDeletion";
import { ModelMarker } from "./ModelMarker";
import { SphereListMarker } from "./SphereListMarker";
import { TextMarker } from "./TextMarker";
import { TriangleListMarker } from "./TriangleListMarker";

/** A list of any number or type of markers */
export type Markers = {
  /** Marker deletion actions */
  deletions: MarkerDeletion[];

  /** Arrow markers */
  arrows: ArrowMarker[];

  /** Cube list markers */
  cubes: CubeListMarker[];

  /** Sphere list markers */
  spheres: SphereListMarker[];

  /** Cone list markers */
  cones: ConeListMarker[];

  /** Line markers */
  lines: LineMarker[];

  /** Triangle list markers */
  triangles: TriangleListMarker[];

  /** Text markers */
  texts: TextMarker[];

  /** Model markers */
  models: ModelMarker[];
};
