// Generated by https://github.com/foxglove/schemas

/** An enumeration indicating which markers should match a MarkerDeletion command */
export enum MarkerDeletionType {
  MATCHING_NAMESPACE_AND_ID = 0,

  MATCHING_NAMESPACE = 1,

  ALL = 2,
}
