// Generated by https://github.com/foxglove/schemas

/** An enumeration indicating which markers should match a MarkerDeletion command */
export enum MarkerDeletionType {
  MATCHING_ID = 0,

  ALL = 1,
}
