// Generated by https://github.com/foxglove/schemas

import { Color } from "./Color";
import { KeyValuePair } from "./KeyValuePair";
import { Pose } from "./Pose";
import { Vector3 } from "./Vector3";

/** A primitive representing a 3D model file loaded from an external URL */
export type ModelPrimitive = {
  /** Origin of model relative to reference frame */
  pose: Pose;

  /** Scale factor to apply to the model along each axis */
  scale: Vector3;

  /** Solid color to use for the whole model. If `use_embedded_materials` is true, this color is blended on top of the embedded material color. */
  color: Color;

  /** Whether to use materials embedded in the model, or only the `color` */
  use_embedded_materials: boolean;

  /** URL pointing to model file. Either `url` or `mime_type` and `data` should be provided. */
  url: string;

  /** MIME type of embedded model (e.g. `model/gltf-binary`). Either `url` or `mime_type` and `data` should be provided. */
  mime_type: string;

  /** Embedded model. Either `url` or `mime_type` and `data` should be provided. */
  data: Uint8Array;

  /** Additional user-provided metadata associated with the model. Keys must be unique. */
  metadata: KeyValuePair[];
};
