// Generated by https://github.com/foxglove/schemas

/** Type of points annotation */
export enum PointsAnnotationType {
  UNKNOWN = 0,

  POINTS = 1,

  LINE_LOOP = 2,

  LINE_STRIP = 3,

  LINE_LIST = 4,
}
