// Generated by https://github.com/foxglove/schemas
// Options: {}

/** A point representing a position in 2D space */
export type Point2 = {
  /** x coordinate position */
  x: number;

  /** y coordinate position */
  y: number;
};
