// Generated by https://github.com/foxglove/schemas

/** Type of position covariance */
export const enum PositionCovarianceType {
  UNKNOWN = 0,

  APPROXIMATED = 1,

  DIAGONAL_KNOWN = 2,

  KNOWN = 3,
}
