// Generated by https://github.com/foxglove/schemas

/** An enumeration indicating which markers should match a PrimitiveDeletion command */
export enum PrimitiveDeletionType {
  MATCHING_ID = 0,

  ALL = 1,
}
