// Generated by https://github.com/foxglove/schemas

import { PrimitiveDeletionType } from "./PrimitiveDeletionType";
import { Time } from "./Time";

/** Command to remove previously published markers */
export type PrimitiveDeletion = {
  /** Timestamp of the marker. Only matching markers earlier than this timestamp will be deleted. */
  timestamp: Time;

  /** Type of deletion action to perform */
  type: PrimitiveDeletionType;

  /** Numeric identifier which must match if `kind` is `MATCHING_ID`. */
  id: string;
};
