// Generated by https://github.com/foxglove/schemas
// Options: {}

/** A [quaternion](https://eater.net/quaternions) representing a rotation in 3D space */
export type Quaternion = {
  /** x value */
  x: number;

  /** y value */
  y: number;

  /** z value */
  z: number;

  /** w value */
  w: number;
};
