// Generated by https://github.com/foxglove/schemas

import { PrimitiveDeletion } from "./PrimitiveDeletion";
import { SceneEntity } from "./SceneEntity";

/** An update to the entities displayed in a 3D scene */
export type SceneEntityUpdate = {
  /** Scene entities to delete */
  deletions: PrimitiveDeletion[];

  /** Scene entities to add or replace */
  entities: SceneEntity[];
};
