// Generated by https://github.com/foxglove/schemas

/** An enumeration indicating which entities should match a SceneEntityDeletion command */
export enum SceneEntityDeletionType {
  MATCHING_ID = 0,

  ALL = 1,
}
