// Generated by https://github.com/foxglove/schemas

import { MarkerDeletion } from "./MarkerDeletion";
import { SceneEntity } from "./SceneEntity";

/** An update to the entities displayed in a 3D scene */
export type SceneEntityUpdate = {
  /** Scene entities to delete */
  deletions: MarkerDeletion[];

  /** Scene entities to add or update */
  entities: SceneEntity[];
};
