// Generated by https://github.com/foxglove/schemas

import { SceneEntityDeletionType } from "./SceneEntityDeletionType";
import { Time } from "./Time";

/** Command to remove previously published entities */
export type SceneEntityDeletion = {
  /** Timestamp of the deletion. Only matching entities earlier than this timestamp will be deleted. */
  timestamp: Time;

  /** Type of deletion action to perform */
  type: SceneEntityDeletionType;

  /** Identifier which must match if `type` is `MATCHING_ID`. */
  id: string;
};
