// Generated by https://github.com/foxglove/schemas

import { Color } from "./Color";
import { Pose } from "./Pose";
import { Vector3 } from "./Vector3";

/** A marker representing a sphere or ellipsoid */
export type SphereMarker = {
  /** Position of the center of the sphere and orientation of the sphere */
  pose: Pose;

  /** Size (diameter) of the sphere along each axis */
  size: Vector3;

  /** Color of the sphere */
  color: Color;
};
