// Generated by https://github.com/foxglove/schemas
// Options: {}

import { Color } from "./Color";
import { Point2 } from "./Point2";
import { Time } from "./Time";

/** A text label on a 2D image */
export type TextAnnotation = {
  /** Timestamp of annotation */
  timestamp: Time;

  /** Bottom-left origin of the text label in 2D image coordinates (pixels) */
  position: Point2;

  /** Text to display */
  text: string;

  /** Font size in pixels */
  font_size: number;

  /** Text color */
  text_color: Color;

  /** Background fill color */
  background_color: Color;
};
