import os

from conans import ConanFile, tools, CMake


class FoxgloveSchemasConan(ConanFile):
    name = "foxglove-schemas"
    version = "1.0.0"
    license = "<Put the package license here>"
    author = "<Put your name here> <And your email here>"
    url = "<Package recipe repository url here, for issues about the package>"
    description = "<Description of FoxgloveSchemas here>"
    topics = ("<Put some tag here>", "<here>", "<and here>")
    settings = "os", "compiler", "build_type", "arch"
    options = {"shared": [True, False]}
    default_options = {"shared": False}  
    exports_sources = "*"
    generators = "cmake_find_package"

    def requirements(self):
        self.requires("protobuf/3.17.1")

    def build(self):
        cmake = CMake(self)
        cmake.configure()
        cmake.build()

    def package(self):
        self.copy("*.proto", src="schemas/proto", dst="include/foxglove", keep_path=False)
        self.copy("*.pb.h", src="autogenerated", dst="include/foxglove", keep_path=False)
        self.copy("*.a", dst="lib", keep_path=False)

    def package_info(self):
        self.cpp_info.libs = ["foxglove-schemas"]
