// Generated by https://github.com/foxglove/schemas
// Options: {}

import { Color } from "./Color";
import { Point2 } from "./Point2";
import { Time } from "./Time";

/** A circle annotation on a 2D image */
export type CircleAnnotation = {
  /** Timestamp of circle */
  timestamp: Time;

  /**
   * Center of the circle in 2D image coordinates (pixels).
   * The coordinate uses the top-left corner of the top-left pixel of the image as the origin.
   */
  position: Point2;

  /** Circle diameter in pixels */
  diameter: number;

  /** Line thickness in pixels */
  thickness: number;

  /** Fill color */
  fill_color: Color;

  /** Outline color */
  outline_color: Color;
};
