// Generated by https://github.com/foxglove/schemas
// Options: {}

import { FrameTransform } from "./FrameTransform";

/** An array of FrameTransform messages */
export type FrameTransforms = {
  /** Array of transforms */
  transforms: FrameTransform[];
};
