// Generated by https://github.com/foxglove/foxglove-sdk
// Options: {}

/** GeoJSON data for annotating maps */
export type GeoJSON = {
  /** GeoJSON data encoded as a UTF-8 string */
  geojson: string;
};
