// Generated by https://github.com/foxglove/schemas
// Options: {}

import { CircleAnnotation } from "./CircleAnnotation";
import { PointsAnnotation } from "./PointsAnnotation";
import { TextAnnotation } from "./TextAnnotation";

/** Array of annotations for a 2D image */
export type ImageAnnotations = {
  /** Circle annotations */
  circles: CircleAnnotation[];

  /** Points annotations */
  points: PointsAnnotation[];

  /** Text annotations */
  texts: TextAnnotation[];
};
