// Generated by https://github.com/foxglove/foxglove-sdk
// Options: {}

/** A key with its associated value */
export type KeyValuePair = {
  /** Key */
  key: string;

  /** Value */
  value: string;
};
