// Generated by https://github.com/foxglove/foxglove-sdk
// Options: {}

/** Log level */
export enum LogLevel {
  UNKNOWN = 0,

  DEBUG = 1,

  INFO = 2,

  WARNING = 3,

  ERROR = 4,

  FATAL = 5,
}
