// Generated by https://github.com/foxglove/foxglove-sdk
// Options: {}

/** Type of position covariance */
export enum PositionCovarianceType {
  UNKNOWN = 0,

  APPROXIMATED = 1,

  DIAGONAL_KNOWN = 2,

  KNOWN = 3,
}
