// Generated by https://github.com/foxglove/schemas
// Options: {}

/** A vector in 2D space that represents a direction only */
export type Vector2 = {
  /** x coordinate length */
  x: number;

  /** y coordinate length */
  y: number;
};
