// Generated by https://github.com/foxglove/schemas
// Options: {}

/** A vector in 3D space that represents a direction only */
export type Vector3 = {
  /** x coordinate length */
  x: number;

  /** y coordinate length */
  y: number;

  /** z coordinate length */
  z: number;
};
