import { program } from "commander";
import { execFileSync, ExecFileSyncOptions } from "node:child_process";
import fs from "node:fs/promises";
import path from "node:path";
import { rimraf } from "rimraf";

import { generateRosMsg, generateRosMsgDefinition } from "../typescript/schemas/src/internal";
import { exportTypeScriptSchemas } from "../typescript/schemas/src/internal/exportTypeScriptSchemas";
import {
  BYTE_VECTOR_FB,
  DURATION_FB,
  TIME_FB,
  generateFlatbuffers,
} from "../typescript/schemas/src/internal/generateFlatbufferSchema";
import { generateJsonSchema } from "../typescript/schemas/src/internal/generateJsonSchema";
import { generateMarkdown } from "../typescript/schemas/src/internal/generateMarkdown";
import {
  DURATION_IDL,
  TIME_IDL,
  generateOmgIdl,
} from "../typescript/schemas/src/internal/generateOmgIdl";
import { generateProto } from "../typescript/schemas/src/internal/generateProto";
import {
  generateModuleRegistration,
  generatePrelude,
  generatePyclass,
  generatePymodule,
  generatePymoduleStub,
  generateTimeTypes,
} from "../typescript/schemas/src/internal/generatePyclass";
import {
  foxgloveEnumSchemas,
  foxgloveMessageSchemas,
} from "../typescript/schemas/src/internal/schemas";

async function logProgress(message: string, body: () => Promise<void>) {
  process.stderr.write(`${message}... `);
  await body();
  process.stderr.write("done\n");
}

async function main({ outDir, rosOutDir }: { outDir: string; rosOutDir: string }) {
  await logProgress("Removing any existing output directory", async () => {
    await rimraf(outDir);
  });

  await logProgress("Generating JSONSchema definitions", async () => {
    await fs.mkdir(path.join(outDir, "jsonschema"), { recursive: true });
    let indexTS = "// Generated by https://github.com/foxglove/schemas\n\n";
    for (const schema of Object.values(foxgloveMessageSchemas)) {
      const json = JSON.stringify(generateJsonSchema(schema), undefined, 2);
      await fs.writeFile(path.join(outDir, "jsonschema", `${schema.name}.json`), json + "\n");
      indexTS += `export const ${schema.name} = ${json};\n\n`;
    }
    await fs.writeFile(path.join(outDir, "jsonschema", `index.ts`), indexTS);
  });

  await logProgress("Generating ROS 1 msg files", async () => {
    await fs.mkdir(path.join(outDir, "ros1"), { recursive: true });
    await fs.mkdir(path.join(rosOutDir, "ros1"), { recursive: true });
    for (const schema of Object.values(foxgloveMessageSchemas)) {
      if (schema.rosEquivalent != undefined) {
        continue;
      }
      const msg = generateRosMsg(generateRosMsgDefinition(schema, { rosVersion: 1 }), {
        rosVersion: 1,
      });
      await fs.writeFile(path.join(outDir, "ros1", `${schema.name}.msg`), msg);
      await fs.writeFile(path.join(rosOutDir, "ros1", `${schema.name}.msg`), msg);
    }
  });

  await logProgress("Generating ROS 2 msg files", async () => {
    await fs.mkdir(path.join(outDir, "ros2"), { recursive: true });
    await fs.mkdir(path.join(rosOutDir, "ros2"), { recursive: true });
    for (const schema of Object.values(foxgloveMessageSchemas)) {
      if (schema.rosEquivalent != undefined) {
        continue;
      }
      const msg = generateRosMsg(generateRosMsgDefinition(schema, { rosVersion: 2 }), {
        rosVersion: 2,
      });
      await fs.writeFile(path.join(outDir, "ros2", `${schema.name}.msg`), msg);
      await fs.writeFile(path.join(rosOutDir, "ros2", `${schema.name}.msg`), msg);
    }
  });

  await logProgress("Generating Protobuf definitions", async () => {
    await fs.mkdir(path.join(outDir, "proto", "foxglove"), { recursive: true });
    for (const schema of Object.values(foxgloveMessageSchemas)) {
      const enums = Object.values(foxgloveEnumSchemas).filter(
        (enumSchema) => enumSchema.parentSchemaName === schema.name,
      );
      await fs.writeFile(
        path.join(outDir, "proto", "foxglove", `${schema.name}.proto`),
        generateProto(schema, enums),
      );
    }
  });

  await logProgress("Generating FlatBuffer definitions", async () => {
    await fs.mkdir(path.join(outDir, "flatbuffer"), { recursive: true });
    await fs.writeFile(path.join(outDir, "flatbuffer", "ByteVector.fbs"), BYTE_VECTOR_FB);
    await fs.writeFile(path.join(outDir, "flatbuffer", "Time.fbs"), TIME_FB);
    await fs.writeFile(path.join(outDir, "flatbuffer", "Duration.fbs"), DURATION_FB);

    for (const schema of Object.values(foxgloveMessageSchemas)) {
      // want enums with their corresponding parent tables for usage
      const enums = Object.values(foxgloveEnumSchemas).filter(
        (enumSchema) => enumSchema.parentSchemaName === schema.name,
      );
      await fs.writeFile(
        path.join(outDir, "flatbuffer", `${schema.name}.fbs`),
        generateFlatbuffers(schema, enums),
      );
    }
  });

  await logProgress("Generating TypeScript definitions", async () => {
    const typesDir = path.join(outDir, "../typescript/schemas/src/types");
    await rimraf(typesDir);
    await fs.mkdir(typesDir, { recursive: true });

    const schemas = exportTypeScriptSchemas();
    for (const [name, source] of schemas.entries()) {
      await fs.writeFile(path.join(typesDir, `${name}.ts`), source);
    }
  });

  await logProgress("Generating OMG IDL definitions", async () => {
    await fs.mkdir(path.join(outDir, "omgidl", "foxglove"), { recursive: true });
    await fs.writeFile(path.join(outDir, "omgidl", "foxglove", "Time.idl"), TIME_IDL);
    await fs.writeFile(path.join(outDir, "omgidl", "foxglove", "Duration.idl"), DURATION_IDL);
    for (const schema of Object.values(foxgloveMessageSchemas)) {
      await fs.writeFile(
        path.join(outDir, "omgidl", "foxglove", `${schema.name}.idl`),
        generateOmgIdl(schema),
      );
    }
    for (const schema of Object.values(foxgloveEnumSchemas)) {
      await fs.writeFile(
        path.join(outDir, "omgidl", "foxglove", `${schema.name}.idl`),
        generateOmgIdl(schema),
      );
    }
  });

  await logProgress("Generating README.md", async () => {
    await fs.writeFile(
      path.join(outDir, "README.md"),
      generateMarkdown(Object.values(foxgloveMessageSchemas), Object.values(foxgloveEnumSchemas)),
    );
  });

  await logProgress("Generating Pyclass definitions", async () => {
    // Pyclass definitions are generated specifically for the SDK, and are not stored in ./schemas
    const repoRoot = path.resolve(__dirname, "..");
    const sdkRoot = path.resolve(repoRoot, "python", "foxglove-sdk");

    // Ignore stdout from spawned commands, but keep stderr
    const execOpts: ExecFileSyncOptions = { stdio: ["ignore", "pipe", "pipe"] };
    // Check for tooling dependencies; skip generation if missing
    try {
      execFileSync("cargo", ["fmt", "--version"], execOpts);
    } catch {
      console.warn("Failed to run rustfmt; skipping pyclass generation");
      return;
    }

    try {
      execFileSync("poetry", ["run", "black", "--version"]);
    } catch {
      console.warn("Failed to run `black` with poetry; skipping pyclass generation");
      return;
    }

    const rustDir = path.join(sdkRoot, "src", "generated");
    const stubDir = path.join(sdkRoot, "python", "foxglove", "_foxglove_py");

    const schemasFile = path.join(rustDir, "schemas.rs");
    const pymoduleFile = path.join(rustDir, "schemas_module.rs");
    const pyiStub = path.join(stubDir, "schemas.pyi");

    // Rust source is re-generated from scratch.
    // Stub file is placed into the existing hierarchy.
    await rimraf(rustDir);
    await fs.mkdir(rustDir, { recursive: true });
    await rimraf(pyiStub);

    // Schemas file
    const writer = (await fs.open(schemasFile, "wx")).createWriteStream();
    writer.write(generatePrelude());

    const enumSchemas = Object.values(foxgloveEnumSchemas);
    for (const enumSchema of enumSchemas) {
      writer.write(generatePyclass(enumSchema));
    }

    writer.write(generateTimeTypes());

    const messageSchemas = Object.values(foxgloveMessageSchemas);
    for (const schema of messageSchemas) {
      writer.write(generatePyclass(schema));
    }

    writer.write(generateModuleRegistration([...enumSchemas, ...messageSchemas]));

    // Pymodule file
    await fs.writeFile(pymoduleFile, generatePymodule([...enumSchemas, ...messageSchemas]));

    try {
      execFileSync("cargo", ["fmt", "--", path.resolve(schemasFile)], execOpts);
      execFileSync("cargo", ["fmt", "--", path.resolve(pymoduleFile)], execOpts);
    } catch (err) {
      console.error("Failed to format rust output");
      console.error(err);
    }

    // Pyi stub file
    await fs.writeFile(pyiStub, generatePymoduleStub([...enumSchemas, ...messageSchemas]));
    try {
      execFileSync("poetry", ["run", "black", path.resolve(pyiStub)], execOpts);
    } catch (err) {
      console.error("Failed to format python output");
      console.error(err);
    }

    writer.end();
  });
}

program
  .requiredOption("-o, --out-dir <dir>", "output directory")
  .requiredOption("--ros-out-dir <dir>", "output directory for additional copies of ROS msgs")
  .action(main);

program.parseAsync().catch(console.error);
