import { generateSchemaPrelude, generatePyclass } from "./generatePyclass";
import { exampleEnum, exampleMessage } from "./testFixtures";

describe("generatePyclass", () => {
  it("generates module header", () => {
    expect(generateSchemaPrelude()).toMatchInlineSnapshot(`
        "//! Definitions for well-known Foxglove schemas
        //! Generated by https://github.com/foxglove/foxglove-sdk
        #![allow(clippy::too_many_arguments)]
        #![allow(clippy::enum_variant_names)]
        #![allow(non_snake_case)]
        use pyo3::{prelude::*, types::PyBytes};

        "
        `);
  });

  it("generates an enum", () => {
    expect(generatePyclass(exampleEnum)).toMatchInlineSnapshot(`
        "/// An example enum
        #[pyclass(eq, eq_int, module = "foxglove.schemas")]
        #[derive(PartialEq, Clone)]
        pub(crate) enum ExampleMessageExampleEnum {
            A = 0,
            B = 1,
        }

        "
        `);
  });

  it("generates a struct from a message", () => {
    expect(generatePyclass(exampleMessage)).toMatchInlineSnapshot(`
        "/// An example type
        #[pyclass(module = "foxglove.schemas")]
        #[derive(Clone)]
        pub(crate) struct ExampleMessage(pub(crate) foxglove::schemas::ExampleMessage);
        #[pymethods]
        impl ExampleMessage {
            #[new]
            #[pyo3(signature = (*, field_duration=None, field_time=None, field_boolean=false, field_bytes=None, field_float64=0.0, field_uint32=0, field_string="".to_string(), field_duration_array=vec![], field_time_array=vec![], field_boolean_array=vec![], field_bytes_array=None, field_float64_array=vec![], field_uint32_array=vec![], field_string_array=vec![], field_duration_fixed_array=vec![], field_time_fixed_array=vec![], field_boolean_fixed_array=vec![], field_bytes_fixed_array=None, field_float64_fixed_array=vec![], field_uint32_fixed_array=vec![], field_string_fixed_array=vec![], field_enum=ExampleMessageExampleEnum::A, field_enum_array=vec![], field_nested=None, field_nested_array=vec![]) )]
            fn new(
                field_duration: Option<Duration>,
                field_time: Option<Timestamp>,
                field_boolean: bool,
                field_bytes: Option<Bound<'_, PyBytes>>,
                field_float64: f64,
                field_uint32: u32,
                field_string: String,
                field_duration_array: Vec<Option<Duration>>,
                field_time_array: Vec<Option<Timestamp>>,
                field_boolean_array: Vec<bool>,
                field_bytes_array: Option<Bound<'_, PyBytes>>,
                field_float64_array: Vec<f64>,
                field_uint32_array: Vec<u32>,
                field_string_array: Vec<String>,
                field_duration_fixed_array: Vec<Option<Duration>>,
                field_time_fixed_array: Vec<Option<Timestamp>>,
                field_boolean_fixed_array: Vec<bool>,
                field_bytes_fixed_array: Option<Bound<'_, PyBytes>>,
                field_float64_fixed_array: Vec<f64>,
                field_uint32_fixed_array: Vec<u32>,
                field_string_fixed_array: Vec<String>,
                field_enum: ExampleMessageExampleEnum,
                field_enum_array: Vec<ExampleMessageExampleEnum>,
                field_nested: Option<NestedMessage>,
                field_nested_array: Vec<NestedMessage>,
            ) -> Self {
                Self(foxglove::schemas::ExampleMessage {
                    field_duration: field_duration.map(Into::into),
                    field_time: field_time.map(Into::into),
                    field_boolean,
                    field_bytes: data.map(|x| x.as_bytes().to_vec()).unwrap_or_default(),
                    field_float64,
                    field_uint32,
                    field_string,
                    field_duration_array: field_duration_array.map(Into::into),
                    field_time_array: field_time_array.map(Into::into),
                    field_boolean_array,
                    field_bytes_array: data.map(|x| x.as_bytes().to_vec()).unwrap_or_default(),
                    field_float64_array,
                    field_uint32_array,
                    field_string_array,
                    field_duration_fixed_array: field_duration_fixed_array.map(Into::into),
                    field_time_fixed_array: field_time_fixed_array.map(Into::into),
                    field_boolean_fixed_array,
                    field_bytes_fixed_array: data.map(|x| x.as_bytes().to_vec()).unwrap_or_default(),
                    field_float64_fixed_array,
                    field_uint32_fixed_array,
                    field_string_fixed_array,
                    field_enum: field_enum as i32,
                    field_enum_array: field_enum_array as i32,
                    field_nested: field_nested.map(Into::into),
                    field_nested_array: field_nested_array.into_iter().map(|x| x.into()).collect(),
                })
            }
            fn __repr__(&self) -> String {
                format!(
                    "ExampleMessage(field_duration={:?}, field_time={:?}, field_boolean={:?}, field_bytes={:?}, field_float64={:?}, field_uint32={:?}, field_string={:?}, field_duration_array={:?}, field_time_array={:?}, field_boolean_array={:?}, field_bytes_array={:?}, field_float64_array={:?}, field_uint32_array={:?}, field_string_array={:?}, field_duration_fixed_array={:?}, field_time_fixed_array={:?}, field_boolean_fixed_array={:?}, field_bytes_fixed_array={:?}, field_float64_fixed_array={:?}, field_uint32_fixed_array={:?}, field_string_fixed_array={:?}, field_enum={:?}, field_enum_array={:?}, field_nested={:?}, field_nested_array={:?})",
                    self.0.field_duration,
                    self.0.field_time,
                    self.0.field_boolean,
                    self.0.field_bytes,
                    self.0.field_float64,
                    self.0.field_uint32,
                    self.0.field_string,
                    self.0.field_duration_array,
                    self.0.field_time_array,
                    self.0.field_boolean_array,
                    self.0.field_bytes_array,
                    self.0.field_float64_array,
                    self.0.field_uint32_array,
                    self.0.field_string_array,
                    self.0.field_duration_fixed_array,
                    self.0.field_time_fixed_array,
                    self.0.field_boolean_fixed_array,
                    self.0.field_bytes_fixed_array,
                    self.0.field_float64_fixed_array,
                    self.0.field_uint32_fixed_array,
                    self.0.field_string_fixed_array,
                    self.0.field_enum,
                    self.0.field_enum_array,
                    self.0.field_nested,
                    self.0.field_nested_array,
                )
            }
        }


        impl From<ExampleMessage> for foxglove::schemas::ExampleMessage {
            fn from(value: ExampleMessage) -> Self {
                value.0
            }
        }

        "
        `);
  });
});
